from enum import Enum
from typing import Union


class ElevatorCallingButton(Enum):
    UP = "UP"
    DOWN = "DOWN"


class Direction(Enum):
    UP = "UP"
    DOWN = "DOWN"
    IDLE = "IDLE"


class FloorEvent(Enum):
    UP_BUTTON_PRESSED_FROM_FLOOR = "UP_BUTTON_PRESSED_FROM_FLOOR"
    DOWN_BUTTON_PRESSED_FROM_FLOOR = "DOWN_BUTTON_PRESSED_FROM_FLOOR"
    ELEVATOR_AVAILABLE_FOR_TRANSPORT = "ELEVATOR_AVAILABLE_FOR_TRANSPORT"


class ElevatorEvent(Enum):
    DESTINATION_FLOOR_PRESSED = "DESTINATION_FLOOR_PRESSED"
    ELEVATOR_REACHED_THE_DESTINATION = "ELEVATOR_REACHED_THE_DESTINATION"
    ELEVATOR_IS_IDLE = "ELEVATOR_IS_IDLE"


class PassengerEvent(Enum):
    PASSENGER_EXITING_FLOOR = "PASSENGER_EXITING_FLOOR"
    PASSENGER_EXITING_ELEVATOR = "PASSENGER_EXITING_ELEVATOR"
    PASSENGER_INSIDE_THE_ELEVATOR = "PASSENGER_INSIDE_THE_ELEVATOR"


Event = Union[FloorEvent, ElevatorEvent, PassengerEvent]
